version: "2"
services:
  zookeeper:
    build: ./zookeeper
    ports:
      - "2181:2181"
    expose:
      - "2181"
  kafka:
    build: ./kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper
